"""lib.gjclasses

contains GJLevel and GJObject
"""

import math as maths  # i am stubborn
from lib import gjcrypt
from lib.strdict import StrDict
from lib.objinfo import obj_info

TENSQRTTWO = 10 * maths.sqrt(2)

# objects that need their secondary colour set rather than primary
# in polzhax white fix. generated by script
SECONDARY_CHANNEL = {
  '207', '208', '209', '210', '212', '213', '215', '216', '217', '218', '219', '220',
  '247', '248', '249', '250', '252', '253', '254', '255', '256', '257', '258', '260',
  '261', '263', '264', '265', '267', '268', '269', '270', '271', '272', '274', '275',
  '331', '333', '337', '339', '343', '345', '349', '351', '353', '355', '397', '398',
  '399', '409', '410', '411', '412', '413', '453', '454', '455', '456', '457', '458',
  '477', '478', '479', '480', '481', '482', '483', '484', '485', '486', '487', '488',
  '489', '490', '491', '492', '493', '641', '642', '643', '644', '645', '646', '647',
  '648', '649', '651', '652', '678', '679', '680', '703', '704', '705', '706', '707',
  '708', '739',
  }

class GJLevel(StrDict):
  """GJLevel(StrDict)
  
  contains geometry dash level info
  """
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.unpacked = False
  
  def unpack(self):
    """decrypts level string and decomposes it into level
    objects
    """
    if self.unpacked:
      return
    obj_strings = gjcrypt.decode_level(self.data_string).split(";")
    self.objects = [GJObject(gjcrypt.decode_kv(x, separator=",")) for x in obj_strings if x]
    self.start_obj = self.objects.pop(0)
    
    self.unpacked = True
  
  def repack(self):
    """repacks all level objects back into level string"""
    self.objects.insert(0, self.start_obj)
    self.data_string = gjcrypt.encode_level("".join(str(x) for x in self.objects))
    
    self.unpacked = False
  
  def upload_info(self):
    """returns upload info, doesn't include account info"""
    if self.unpacked:
      self.repack()
    return {
      "levelID": 0,
      "levelName": self.name,
      "levelDesc": self.description,
      "levelVersion": 1,
      "levelLength": self.length,
      "audioTrack": self.default_song_id,
      "auto": 0,
      "password": self.password,
      "original": 0,
      "twoPlayer": self.is_two_player,
      "songID": self.custom_song_id,
      "objects": self.object_count,
      "coins": 0,
      "requestedStars": 0,
      "unlisted": 0,
      "ldm": 0,
      "levelString": self.data_string,
      "seed2": gjcrypt.make_level_seed(self.data_string),
      }
  
  # boilerplate pt 1
  @property
  def id(self):
    return self[1]
  @id.setter
  def id(self, v):
    self[1] = v
  
  @property
  def name(self):
    return self[2]
  @name.setter
  def name(self, v):
    self[2] = v
  
  @property
  def description(self):
    return self[3]
  @description.setter
  def description(self, v):
    self[3] = v
  
  @property
  def data_string(self):
    return self[4]
  @data_string.setter
  def data_string(self, v):
    self[4] = v
  
  @property
  def uploader_player_id(self):
    return self[6]
  @uploader_player_id.setter
  def uploader_player_id(self, v):
    self[6] = v
  
  @property
  def default_song_id(self):
    return self[12]
  @default_song_id.setter
  def default_song_id(self, v):
    self[12] = v
  
  @property
  def length(self):
    return self[15]
  @length.setter
  def length(self, v):
    self[15] = v
  
  @property
  def password(self):
    return self[27]
  @password.setter
  def password(self, v):
    self[27] = v
  
  @property
  def is_two_player(self):
    return self[31]
  @is_two_player.setter
  def is_two_player(self, v):
    self[31] = int(v)
  
  @property
  def custom_song_id(self):
    return self[35]
  @custom_song_id.setter
  def custom_song_id(self, v):
    self[35] = v
  
  @property
  def object_count(self):
    return self[45]
  @object_count.setter
  def object_count(self, v):
    self[45] = v
  
  @property
  def song_offset(self):
    if not self.unpacked:
      self.unpack()
    return self.start_obj["kA13"]
  @song_offset.setter
  def song_offset(self, v):
    if not self.unpacked:
      self.unpack()
    self.start_obj["kA13"] = v
  
  @property
  def song_fadein(self):
    if not self.unpacked:
      self.unpack()
    return self.start_obj["kA15"]
  @song_fadein.setter
  def song_fadein(self, v):
    if not self.unpacked:
      self.unpack()
    self.start_obj["kA15"] = int(v)
  
  @property
  def song_fadeout(self):
    if not self.unpacked:
      self.unpack()
    return self.start_obj["kA16"]
  @song_fadeout.setter
  def song_fadeout(self, v):
    if not self.unpacked:
      self.unpack()
    self.start_obj["kA16"] = int(v)


class GJObject(StrDict):
  """GJObject(StrDict)
  
  contains geometry dash object info, and functions used to
  manipulate said objects
  """
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
  
  def __str__(self):
    return gjcrypt.encode_kv(self, separator=",") + ";"

  def fix_layer(self):
    """uses 2.1 z layer and z order properties to emulate 1.9
    layering
    """
    try:
      info = obj_info[self.id]
    except KeyError:
      return
    
    col = self.colour
    if info["hasColourChild"]:
      col = 0
    elif info["hasChildObj"]:
      col = self.default_colour
    bottom = (info["z"] < 0)
    if col not in {1, 2, 5}:
      bottom |= info["forceBottom"]
    
    self.z_layer = 2 if bottom else 4
    self.z_order = info["z"]
  
  def fix_visual_bugs(self):
    """fixes/reintroduces various visual bugs that exist in either
    1.9 or 2.1 but not both
    """
    if self.id in {"62", "66", "65", "68", "63", "64", "294", "295", "296", "297"}:
      self.main_hsv_enabled = True
      self.main_hsv_string = "0a1a0.02a0a1"
    elif 560 <= int(self.id) <= 577:
      self.main_hsv_enabled = True
      self.main_hsv_string = "0a0a1a0a1"
    
    if self.id in {"36", "63", "64", "67", "84", "140", "141"}:
      self.disable_glow = True
  
  def is_white(self):
    return self.get(21, self.get(22, None)) == 1011 or self.colour not in \
        {0, 1, 2, 3, 4, 5, 6, 7, 8}
  
  def polz_white_fix(self):
    """fixes polzhax white channel not correctly transferring over to 2.2
    """
    print(self.colour)
    if self.is_white():
      # set 2.0 channel id to 2.1 white
      if self.id in SECONDARY_CHANNEL:
        self[22] = 1011
      else:
        self[21] = 1011
      # remove 1.9 colour channel id so it doesn't interfere
      self.pop(19, None)
  
  def init_glow_corner_values(self):
    """initialises corner values for glow dot merging"""
    offset = self.flip_x*3 ^ self.flip_y
    self.angle = (int(self.rotation) - offset*90) % 360
    
    temp = maths.radians(self.angle + 135)
    self.centre = (
      self.x + maths.sin(temp)*TENSQRTTWO,
      self.y + maths.cos(temp)*TENSQRTTWO,
      )
    colour = 9 if self.is_white() else self.colour
    self.merge_group = (colour, self.angle % 90)
    self.subgroup = (self.angle - self.merge_group[1]) // 90
  
  # boilerplate pt 2
  @property
  def id(self):
    return self[1]
  @id.setter
  def id(self, v):
    self[1] = v
  
  @property
  def x(self):
    return float(self[2])
  @x.setter
  def x(self, v):
    self[2] = v
  
  @property
  def y(self):
    return float(self[3])
  @y.setter
  def y(self, v):
    self[3] = v
  
  @property
  def flip_x(self):
    return bool(int(self.get(4, 0)))
  @flip_x.setter
  def flip_x(self, v):
    self[4] = int(v)
  
  @property
  def flip_y(self):
    return bool(int(self.get(5, 0)))
  @flip_y.setter
  def flip_y(self, v):
    self[5] = int(v)
  
  @property
  def rotation(self):
    return float(self.get(6, 0))
  @rotation.setter
  def rotation(self, v):
    self[6] = v
  
  @property
  def default_colour(self):
    try:
      return self._default_colour
    except AttributeError:
      try:
        info = obj_info[self.id]
      except KeyError:
        default = 0
      else:
        default = info["defaultCol"]
      self._default_colour = default
      return default
  
  @property
  def colour(self):
    return int(self.get(19, self.default_colour))
  @colour.setter
  def colour(self, v):
    self[19] = v
  
  @property
  def z_layer(self):
    return int(self.get(24, 0))
  @z_layer.setter
  def z_layer(self, v):
    self[24] = v
  
  @property
  def z_order(self):
    return int(self.get(25, 0))
  @z_order.setter
  def z_order(self, v):
    self[25] = v
  
  @property
  def main_hsv_enabled(self):
    return bool(int(self.get(41, 0)))
  @main_hsv_enabled.setter
  def main_hsv_enabled(self, v):
    self[41] = int(v)
  
  @property
  def main_hsv_string(self):
    return self.get(43, 0)
  @main_hsv_string.setter
  def main_hsv_string(self, v):
    self[43] = v
  
  @property
  def disable_glow(self):
    return bool(int(self.get(96, 0)))
  @disable_glow.setter
  def disable_glow(self, v):
    self[96] = int(v)
